services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server-container
    networks:
      - htw-net
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client-container
    depends_on:
      - server
    networks:
      - htw-net

networks:
  htw-net:
    driver: bridge
